export const ACTIONS = {
    LOAD_CLIENTS: 'LOAD_CLIENTS',
    LOAD_GEOFENCES: 'LOAD_GEOFENCES',
    LOAD_DISTRIBUTORS: 'LOAD_DISTRIBUTORS',
    UPDATE_FILTERS: 'UPDATE_FILTERS',
    UPDATE_SWITCH: 'UPDATE_SWITCH',
    SET_USER: 'SET_USER',
    SET_VISIT_STATUS: 'SET_VISIT_STATUS',
    SET_OPTIMIZED_ROUTE: 'SET_OPTIMIZED_ROUTE',
    CLEAR_OPTIMIZED_ROUTE: 'CLEAR_OPTIMIZED_ROUTE'
};
